# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc" do
  version "1.27.1"

  on_macos do
    on_arm do
      sha256 "ced70a732663b7fae53bb89b62165eb77bddd83eebc7b011256f58de0e103b12"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb2678c88dac22ad626343e048701f83ca9ec916d0909826e50275e14b1356d6"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd577280ccab46834e7fa3de7f3cfbf0316962c88017b371cb2a0982a61c1102"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "36cd54befe043ade8a2bd3f8ff89624bdca8170fbcca4a3f95db1228e0f0b3d9"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rc"
  desc "Thin scriptable client over rootcause's /api/v1 — consume your project's own run data"
  homepage "https://github.com/rootcause-org/rootcause-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rc"]
    end
  end

  # No zap stanza required
end
