# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "5c42582f49ded3ba0830605f0d5acdc8afb0727acd93bad16b377d1635ba0d05"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "87e49e34e3616c515a7fde59ee1fcb7dedcc93712275d6eb9852d96b0be35ac3"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "265593dac56c2d959838a6532c35b288a3534e9f6f44adf82b2f827210e9a11d"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04cb2cd8141b74b0c1ee0a2649f881e93a92dc41679e995abf3c15c953bb72a4"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rc"
  desc "Thin scriptable client over rootcause's /api/v1 — consume your project's own run data"
  homepage "https://github.com/rootcause-org/rootcause-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rc"]
    end
  end

  # No zap stanza required

end
