# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc" do
  version "1.1.3"

  on_macos do
    on_intel do
      sha256 "3d40107f061d0c55cf2c7c4c3d6385b27e5f8e89acb13e413e8d1bb9e1628e5c"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1a3448323f428fcc69e757cd5a2e7e7d5f0d88034f43efbb5565589bf649fd2"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adf45268c98f4f660bdfbc46d421b0be558414b7521a2a7cf640c5b132d8e775"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ff36c3c065002528785e407652ce31381dc31a3a66ac7de139417a3c73c3cdf"
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v#{version}/rc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rc"
  desc "Thin scriptable client over rootcause's /api/v1 — consume your project's own run data"
  homepage "https://github.com/rootcause-org/rootcause-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rc"]
    end
  end

  # No zap stanza required

end
