# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rc < Formula
  desc "Thin scriptable client over rootcause's /api/v1 — consume your project's own run data"
  homepage "https://github.com/rootcause-org/rootcause-cli"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.2.2/rc_0.2.2_darwin_amd64.tar.gz"
      sha256 "df1ffdc491e92e031fabf7fbe3e063aad402e2d6c04f3caf77ede50b0741fe12"

      define_method(:install) do
        bin.install "rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.2.2/rc_0.2.2_darwin_arm64.tar.gz"
      sha256 "1cbda16ab87601cff06e315329fe8ab75e3ecd8dcf9f0f5a9bef7c53ed90fc56"

      define_method(:install) do
        bin.install "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.2.2/rc_0.2.2_linux_amd64.tar.gz"
      sha256 "66178c858df6f86ea038a9e7124d33ccfc891f0a49b13aea2bc84d68d03f58b1"
      define_method(:install) do
        bin.install "rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.2.2/rc_0.2.2_linux_arm64.tar.gz"
      sha256 "007bf21ce5863cccdef573b3dde37f1c74de527e67c7f78b8d0ab45432437a07"
      define_method(:install) do
        bin.install "rc"
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
  end
end
