# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rc < Formula
  desc "Thin scriptable client over rootcause's /api/v1 — consume your project's own run data"
  homepage "https://github.com/rootcause-org/rootcause-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.5.0/rc_0.5.0_darwin_amd64.tar.gz"
      sha256 "96d42c4ce525a17841455a6e8ccbff2e04f918b8c7a47b10ad9ded46372e9d7e"

      define_method(:install) do
        bin.install "rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.5.0/rc_0.5.0_darwin_arm64.tar.gz"
      sha256 "0ac48223054b6dbd0812ae3002eaadf9b9b33ce358f0d5facb52a214bff07d02"

      define_method(:install) do
        bin.install "rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.5.0/rc_0.5.0_linux_amd64.tar.gz"
      sha256 "a18c3522f908e5cdcb250ad00634a7dabdf5865fdebb3bdd8216ef1b95efe17a"
      define_method(:install) do
        bin.install "rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rootcause-org/rootcause-cli/releases/download/v0.5.0/rc_0.5.0_linux_arm64.tar.gz"
      sha256 "e46d85027d53ddd622f74fc260023e332c17815561983ce54d71acb266a734e7"
      define_method(:install) do
        bin.install "rc"
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
  end
end
